### ISSUE TITLE
FR: Global toggle command

### ISSUE THREAD

**Issue by iamrecursion** [artisticat1/nl-syntax-highlighting#5]
It would be great to be able to toggle this globally as it isn't always feasible to add a frontmatter field to turn this on.

**Comment by StefanoRausch** [comment]
For the time being you can use the `Plugin Groups` plugin ([obsidian://show-plugin?id=obsidian-plugin-groups](obsidian://show-plugin?id=obsidian-plugin-groups)) to disable and enable specific plugins on the fly.

**Comment by artisticat1** [comment]
I'd be happy to accept a PR for this feature!

**Comment by StefanoRausch** [comment]
> For the time being you can use the `Plugin Groups` plugin (obsidian://show-plugin?id=obsidian-plugin-groups) to disable and enable specific plugins on the fly.

I found out that you can use the BRAT plugin as well to dis- / enable plugins too.

**Comment by artisticat1** [comment]
Added in the latest release! You can toggle the highlighting on or off via the command **Natural Language Syntax Highlighting: Toggle on/off**, thanks to #18 by @Nick-de-Bruin.
